export const userGroupList = [
  {
    is_disabled: false,
    role_name_list: ['roleName3', 'roleName2', 'roleName'],
    user_group_desc: '袁桂英',
    user_group_name: 'Williams1',
    user_name_list: [],
  },
  {
    is_disabled: true,
    role_name_list: ['roleName3', 'roleName', 'roleName2'],
    user_group_desc: '黎秀兰',
    user_group_name: 'Harris2',
    user_name_list: ['user2'],
  },
  {
    is_disabled: false,
    role_name_list: ['roleName', 'roleName2', 'roleName3'],
    user_group_desc: '钱磊',
    user_group_name: 'Young3',
    user_name_list: ['user2'],
  },
  {
    is_disabled: true,
    role_name_list: ['roleName2'],
    user_group_desc: '谢秀英',
    user_group_name: 'Lee4',
    user_name_list: [],
  },
  {
    is_disabled: true,
    role_name_list: [],
    user_group_desc: '叶艳',
    user_group_name: 'Allen',
    user_name_list: [],
  },
  {
    is_disabled: true,
    role_name_list: ['roleName3'],
    user_group_desc: '姜娟',
    user_group_name: 'Jackson4',
    user_name_list: [],
  },
  {
    is_disabled: false,
    role_name_list: ['roleName3', 'roleName'],
    user_group_desc: '袁磊',
    user_group_name: 'Johnson6',
    user_name_list: ['user2'],
  },
  {
    is_disabled: false,
    role_name_list: ['roleName', 'roleName3'],
    user_group_desc: '秦敏',
    user_group_name: 'Martinez7',
    user_name_list: [],
  },
  {
    is_disabled: true,
    role_name_list: ['roleName3'],
    user_group_desc: '吕超',
    user_group_name: 'Martinez8',
    user_name_list: [],
  },
  {
    is_disabled: false,
    role_name_list: ['roleName2', 'roleName3', 'roleName'],
    user_group_desc: '曾杰',
    user_group_name: 'Wilson9',
    user_name_list: [],
  },
];
