export const RoleListData = [
  {
    instance_name_list: ['instance3', 'instance2', 'instance'],
    operation_list: [
      { operation_code: '20150', operation_desc: '查看他人创建的工单' },
      { operation_code: '20400', operation_desc: '删除工单' },
    ],
    role_desc: '陆桂英',
    role_name: 'Taylor',
    user_group_name_list: ['group2', 'group1'],
    user_name_list: ['user1', 'user2'],
    is_disabled: true,
  },
  {
    instance_name_list: ['instance3', 'instance', 'instance2'],
    operation_list: [
      { operation_code: '20300', operation_desc: '创建工单' },
      { operation_code: '20150', operation_desc: '查看他人创建的工单' },
      { operation_code: '20100', operation_desc: '查看工单' },
      { operation_code: '20400', operation_desc: '删除工单' },
      { operation_code: '20200', operation_desc: '更新工单' },
    ],
    role_desc: '宋超',
    role_name: 'White',
    user_group_name_list: ['group1'],
    user_name_list: ['user2'],
    is_disabled: false,
  },
  {
    instance_name_list: ['instance'],
    operation_list: [
      { operation_code: '20150', operation_desc: '查看他人创建的工单' },
      { operation_code: '20100', operation_desc: '查看工单' },
      { operation_code: '20200', operation_desc: '更新工单' },
      { operation_code: '20300', operation_desc: '创建工单' },
    ],
    role_desc: '邱刚',
    role_name: 'Robinson2',
    user_group_name_list: [],
    user_name_list: ['user2'],
  },
  {
    instance_name_list: ['instance3', 'instance', 'instance2'],
    operation_list: [
      { operation_code: '20150', operation_desc: '查看他人创建的工单' },
      { operation_code: '20400', operation_desc: '删除工单' },
      { operation_code: '20300', operation_desc: '创建工单' },
      { operation_code: '20100', operation_desc: '查看工单' },
    ],
    role_desc: '萧秀兰',
    role_name: 'Jones',
    user_group_name_list: [],
    user_name_list: ['user2'],
  },
  {
    instance_name_list: ['instance2'],
    operation_list: [
      { operation_code: '20400', operation_desc: '删除工单' },
      { operation_code: '20300', operation_desc: '创建工单' },
      { operation_code: '20200', operation_desc: '更新工单' },
      { operation_code: '20100', operation_desc: '查看工单' },
    ],
    role_desc: '傅杰',
    role_name: 'Hall',
    user_group_name_list: [],
    user_name_list: [],
  },
  {
    instance_name_list: ['instance3', 'instance2', 'instance'],
    operation_list: [
      { operation_code: '20400', operation_desc: '删除工单' },
      { operation_code: '20150', operation_desc: '查看他人创建的工单' },
      { operation_code: '20100', operation_desc: '查看工单' },
      { operation_code: '20200', operation_desc: '更新工单' },
    ],
    role_desc: '方杰',
    role_name: 'Thomas',
    user_group_name_list: ['group1', 'group2'],
    user_name_list: [],
  },
  {
    instance_name_list: ['instance', 'instance3', 'instance2'],
    operation_list: [
      { operation_code: '20400', operation_desc: '删除工单' },
      { operation_code: '20150', operation_desc: '查看他人创建的工单' },
    ],
    role_desc: '郝明',
    role_name: 'Jackson',
    user_group_name_list: [],
    user_name_list: ['user2'],
  },
  {
    instance_name_list: ['instance2', 'instance', 'instance3'],
    operation_list: [
      { operation_code: '20100', operation_desc: '查看工单' },
      { operation_code: '20200', operation_desc: '更新工单' },
      { operation_code: '20300', operation_desc: '创建工单' },
      { operation_code: '20150', operation_desc: '查看他人创建的工单' },
      { operation_code: '20400', operation_desc: '删除工单' },
    ],
    role_desc: '贾刚',
    role_name: 'Lewis',
    user_group_name_list: ['group1', 'group2'],
    user_name_list: ['user1'],
  },
  {
    instance_name_list: [],
    operation_list: [
      { operation_code: '20200', operation_desc: '更新工单' },
      { operation_code: '20300', operation_desc: '创建工单' },
      { operation_code: '20400', operation_desc: '删除工单' },
      { operation_code: '20100', operation_desc: '查看工单' },
      { operation_code: '20150', operation_desc: '查看他人创建的工单' },
    ],
    role_desc: '锺军',
    role_name: 'Lee',
    user_group_name_list: ['group1'],
    user_name_list: ['user1'],
  },
  {
    instance_name_list: ['instance3'],
    operation_list: [
      { operation_code: '20400', operation_desc: '删除工单' },
      { operation_code: '20300', operation_desc: '创建工单' },
      { operation_code: '20100', operation_desc: '查看工单' },
      { operation_code: '20150', operation_desc: '查看他人创建的工单' },
    ],
    role_desc: '罗杰',
    role_name: 'Harris',
    user_group_name_list: [],
    user_name_list: ['user1', 'user2'],
  },
];
