export const ruleTemplateListData = [
  {
    rule_template_name: 'default',
    desc: '默认规则模板',
    rule_name_list: [
      'all_check_where_is_invalid',
      'ddl_check_alter_table_need_merge',
      'ddl_check_column_blob_default_is_not_null',
      'ddl_check_column_blob_with_not_null',
      'ddl_check_column_char_length',
      'ddl_check_column_timestamp_without_default',
      'ddl_check_column_varchar_max',
      'ddl_check_column_without_comment',
      'ddl_check_column_without_default',
      'ddl_check_composite_index_max',
      'ddl_check_index_column_with_blob',
      'ddl_check_index_count',
      'ddl_check_index_prefix',
      'ddl_check_object_name_length',
      'ddl_check_object_name_using_cn',
      'ddl_check_object_name_using_keyword',
      'ddl_check_pk_not_exist',
      'ddl_check_pk_without_auto_increment',
      'ddl_check_pk_without_bigint_unsigned',
      'ddl_check_table_without_comment',
      'ddl_check_table_without_if_not_exists',
      'ddl_check_table_without_innodb_utf8mb4',
      'ddl_check_unique_index_prefix',
      'ddl_disable_drop_statement',
      'ddl_disable_fk',
      'ddl_osc_min_size',
      'dml_check_with_limit',
      'dml_check_with_order_by',
      'dml_disable_select_all_column',
      'dml_rollback_max_rows',
    ],
  },
  {
    rule_template_name: 'default2',
    desc: '默认规则模板2',
    rule_name_list: [
      'ddl_osc_min_size',
      'dml_check_with_limit',
      'dml_check_with_order_by',
      'dml_disable_select_all_column',
      'dml_rollback_max_rows',
    ],
  },
];

export const ruleTemplateData = {
  rule_template_name: 'default',
  desc: '默认规则模板',
  rule_name_list: [
    'all_check_where_is_invalid',
    'ddl_check_alter_table_need_merge',
    'ddl_check_column_blob_default_is_not_null',
    'ddl_check_column_blob_with_not_null',
    'ddl_check_column_char_length',
    'ddl_check_column_timestamp_without_default',
    'ddl_check_column_varchar_max',
    'ddl_check_column_without_comment',
    'ddl_check_column_without_default',
    'ddl_check_composite_index_max',
    'ddl_check_index_column_with_blob',
    'ddl_check_index_count',
    'ddl_check_index_prefix',
    'ddl_check_object_name_length',
    'ddl_check_object_name_using_cn',
    'ddl_check_object_name_using_keyword',
    'ddl_check_pk_not_exist',
    'ddl_check_pk_without_auto_increment',
    'ddl_check_pk_without_bigint_unsigned',
    'ddl_check_table_without_comment',
    'ddl_check_table_without_if_not_exists',
    'ddl_check_table_without_innodb_utf8mb4',
    'ddl_check_unique_index_prefix',
    'ddl_disable_drop_statement',
    'ddl_disable_fk',
    'ddl_osc_min_size',
    'dml_check_with_limit',
    'dml_check_with_order_by',
    'dml_disable_select_all_column',
    'dml_rollback_max_rows',
  ],
};
