export const UserListData = [
  {
    email: 'a.nnrhdj@uondqxze.ph',
    is_disabled: false,
    login_type: 'sqle',
    role_name_list: [],
    user_group_name_list: ['group'],
    user_name: 'admin',
    phone: '13312341234',
  },
  {
    email: 'l.cjfetom@gqdrfj.lk',
    is_disabled: true,
    login_type: 'ldap',
    role_name_list: ['roleName'],
    user_group_name_list: [],
    user_name: '孙艳',
    phone: '13312345678',
  },
  {
    email: 'l.vxrphnpbtt@wxxmrawkh.st',
    is_disabled: true,
    login_type: 'sqle',
    role_name_list: ['roleName'],
    user_group_name_list: ['group'],
    user_name: '任敏',
  },
  {
    email: 'h.vpbbjqv@prmtjvr.lb',
    is_disabled: true,
    login_type: 'ldap',
    role_name_list: ['roleName'],
    user_group_name_list: [],
    user_name: '贾娜',
  },
  {
    email: 'b.yuuaipnvn@yxthkee.cq',
    is_disabled: true,
    login_type: 'sqle',
    role_name_list: ['roleName', 'roleName1'],
    user_group_name_list: ['group'],
    user_name: '董静',
  },
  {
    email: 'y.bxudhff@cktuxucydm.ca',
    is_disabled: false,
    login_type: 'ldap',
    role_name_list: [],
    user_group_name_list: ['group'],
    user_name: '邱丽',
  },
  {
    email: 'l.enlvcrn@xgevp.uk',
    is_disabled: false,
    login_type: 'sqle',
    role_name_list: ['roleName'],
    user_group_name_list: ['group1', 'group2'],
    user_name: '王敏',
  },
  {
    email: 'z.uljbefgd@rdvsi.lr',
    is_disabled: true,
    login_type: 'ldap',
    role_name_list: ['roleName', 'roleName1'],
    user_group_name_list: ['group'],
    user_name: '孔静',
  },
  {
    email: 'n.tlam@ilrqhnsito.tf',
    is_disabled: false,
    login_type: 'sqle',
    role_name_list: [],
    user_group_name_list: [],
    user_name: '黎洋',
  },
  {
    email: 'v.otxzpusup@bubxdfulx.id',
    is_disabled: false,
    login_type: 'ldap',
    role_name_list: ['roleName', 'roleName1'],
    user_group_name_list: ['group'],
    user_name: '金超',
  },
];
